### ISSUE TITLE
Make Task Cards for sprint 1 (Todo Week 1)

### ISSUE THREAD

**Issue by annagabain** [annagabain/fabulous-sheriffs-grupprojekt-react#13]
**Task:**  Copy and paste tasks from the #1  Sprint 1: Set Up Project, Global States & API Configuration

- [x] Make Task Cards for sprint 1

- [x]  Place the cards in Todo Week 1 column

- [x] assign participants
- [ ] assign start and due dates

  - **Priority:** [High/Medium/Low]
  - **Value Points:** [Number of points]
  - **Estimated Time:** [Estimated time to complete, e.g., 1 hour]
  - **Tags:** [Tags, e.g., `js/react`, `api`, `css`, `html`, `context`, etc.]
  - **Assignee:** [Name of the assignee]
